name: "Computer Science Academy @ Galileo"
description: "Computer Science Academy @ Galileo"

url: "http://csagalileo.github.io"

markdown: rdiscount
permalink: none

timezone: US/Pacific

pygments: true
github: [Repository metadata]
